#version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command: start-dev
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - app-network

  osrm:
    image: osrm/osrm-backend:latest
    container_name: osrm_service
    command: osrm-routed /data/argentina-251105.osrm
    ports:
      - "5000:5000"
    volumes:
      - ./osrm-data:/data
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  apigateway:
    build: ./APIGateway
    container_name: apigateway_ms
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/app_db
      - SPRING_DATASOURCE_USERNAME=usuario
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres
    networks:
      - app-network

  ms-gestiondeinfraestructura:
    build: ./ms-GestionDeInfraestructura
    container_name: infraestructura_ms
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/app_db
      - SPRING_DATASOURCE_USERNAME=usuario
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres
    networks:
      - app-network

  ms-gestiondeoperaciones:
    build: ./ms-GestionDeOperaciones
    container_name: operaciones_ms
    ports:
      - "8083:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/app_db
      - SPRING_DATASOURCE_USERNAME=usuario
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres
    networks:
      - app-network

  ms-gestiondetransporte:
    build: ./ms-GestionDeTransporte
    container_name: transporte_ms
    ports:
      - "8084:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/app_db
      - SPRING_DATASOURCE_USERNAME=usuario
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
  keycloak_data:
